/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1TicketsBookRouteImport } from './routes/api/v1/tickets/book'
import { Route as ApiV1AiStadiumAssistantRouteImport } from './routes/api/v1/ai/stadium-assistant'
import { Route as ApiV1AdminBypassRouteRouteImport } from './routes/api/v1/admin/bypass-route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsBookRoute = ApiV1TicketsBookRouteImport.update({
  id: '/api/v1/tickets/book',
  path: '/api/v1/tickets/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AiStadiumAssistantRoute = ApiV1AiStadiumAssistantRouteImport.update({
  id: '/api/v1/ai/stadium-assistant',
  path: '/api/v1/ai/stadium-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminBypassRouteRoute = ApiV1AdminBypassRouteRouteImport.update({
  id: '/api/v1/admin/bypass-route',
  path: '/api/v1/admin/bypass-route',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/admin/bypass-route': typeof ApiV1AdminBypassRouteRoute
  '/api/v1/ai/stadium-assistant': typeof ApiV1AiStadiumAssistantRoute
  '/api/v1/tickets/book': typeof ApiV1TicketsBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/admin/bypass-route': typeof ApiV1AdminBypassRouteRoute
  '/api/v1/ai/stadium-assistant': typeof ApiV1AiStadiumAssistantRoute
  '/api/v1/tickets/book': typeof ApiV1TicketsBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/admin/bypass-route': typeof ApiV1AdminBypassRouteRoute
  '/api/v1/ai/stadium-assistant': typeof ApiV1AiStadiumAssistantRoute
  '/api/v1/tickets/book': typeof ApiV1TicketsBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/v1/admin/bypass-route'
    | '/api/v1/ai/stadium-assistant'
    | '/api/v1/tickets/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/v1/admin/bypass-route'
    | '/api/v1/ai/stadium-assistant'
    | '/api/v1/tickets/book'
  id:
    | '__root__'
    | '/'
    | '/api/v1/admin/bypass-route'
    | '/api/v1/ai/stadium-assistant'
    | '/api/v1/tickets/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1AdminBypassRouteRoute: typeof ApiV1AdminBypassRouteRoute
  ApiV1AiStadiumAssistantRoute: typeof ApiV1AiStadiumAssistantRoute
  ApiV1TicketsBookRoute: typeof ApiV1TicketsBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/book': {
      id: '/api/v1/tickets/book'
      path: '/api/v1/tickets/book'
      fullPath: '/api/v1/tickets/book'
      preLoaderRoute: typeof ApiV1TicketsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ai/stadium-assistant': {
      id: '/api/v1/ai/stadium-assistant'
      path: '/api/v1/ai/stadium-assistant'
      fullPath: '/api/v1/ai/stadium-assistant'
      preLoaderRoute: typeof ApiV1AiStadiumAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/bypass-route': {
      id: '/api/v1/admin/bypass-route'
      path: '/api/v1/admin/bypass-route'
      fullPath: '/api/v1/admin/bypass-route'
      preLoaderRoute: typeof ApiV1AdminBypassRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1AdminBypassRouteRoute: ApiV1AdminBypassRouteRoute,
  ApiV1AiStadiumAssistantRoute: ApiV1AiStadiumAssistantRoute,
  ApiV1TicketsBookRoute: ApiV1TicketsBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
